#!/usr/bin/env python
# -*- coding: utf-8 -*-

import pyscreenshot as ImageGrab

if __name__ == '__main__':

  # grab fullscreen
  im = ImageGrab.grab()

  # save image file
  im.save('screenshots/screenshot.png')

  # show image in a window
  #im.show()
  #-#
