python find_center.py /local/dataraid/tomo/Choo/D1_B1  
python find_center.py /local/dataraid/tomo/Choo/D1_T5	  
python find_center.py /local/dataraid/tomo/Choo/L1_B5  
python find_center.py /local/dataraid/tomo/Choo/Ni_R1_B1  
python find_center.py /local/dataraid/tomo/Choo/Ni_R1_T5  
python find_center.py /local/dataraid/tomo/Choo/R1_T1  
python find_center.py /local/dataraid/tomo/Choo/Ti64_Pwd
python find_center.py /local/dataraid/tomo/Choo/D1_B5  
python find_center.py /local/dataraid/tomo/Choo/IN738_Pwd  
python find_center.py /local/dataraid/tomo/Choo/L1_T1  
python find_center.py /local/dataraid/tomo/Choo/Ni_R1_B5  
python find_center.py /local/dataraid/tomo/Choo/R1_B1     
python find_center.py /local/dataraid/tomo/Choo/R1_T5
python find_center.py /local/dataraid/tomo/Choo/D1_T1  
python find_center.py /local/dataraid/tomo/Choo/L1_B1	  
python find_center.py /local/dataraid/tomo/Choo/L1_T5  
python find_center.py /local/dataraid/tomo/Choo/Ni_R1_T1  
python find_center.py /local/dataraid/tomo/Choo/R1_B5